### ISSUE TITLE
Oct 16th morning comments

### ISSUE THREAD

**Issue by powdersteep** [davidaries/Job1#1]
I remember there was somewhere I could put comments/issues on existing code, am trying out this spot, but if it should be elsewhere, let's discuss.

Issues at of today:
- I'd intended the timer to just show the seconds since the program launched, and to increment those. When you put in the actual clock time instead, that seemed okay, but now I realize it is indeed an issue. 
- Because what the Pause button is supposed to do is the pause marching forward of time - and therefore also what displays on the timer
- This keeps things like people entering or departing, and the time at which they do so as shown in the log, in synch with what is specified in the initial data, and the timer as displayed. 
- So, if I hit pause when the timer says 0:03, the timer stops, and the log will have shown that the Bill arrived at 0:02. If I stare at the screen for 20 seconds, looking around at various things, and then hit un-pause, the timer continues to 0:03, 0:04, ...., so Faith can come in at 0:06, etc.   The time does not restart at 0:23 because paused for twenty seconds. 
- The end button should actually end the execution of the program. As it is, it only changes lblTest to END, but the program doesn't quit. Actually, I don't see any purpose for lblTest.

Let's talk if any of that is unclear.

**Comment by davidaries** [comment]
issue has been solved in previous commits
